#ifndef __COLORS__
#define __COLORS__
#define BLACK "\e[0;30m"
#define RED "\e[0;31m"
#define GREEN "\e[0;32m"
#define YELLOW "\e[0;33m"
#define BLUE "\e[0;34m"
#define PURPLE "\e[0;35m"
#define CYAN "\e[0;36m"
#define WHITE "\e[0;37m"
#define BLACK_BOLD "\e[1;30m" 
#define RED_BOLD "\e[1;31m" 
#define GREEN_BOLD "\e[1;32m" 
#define YELLOW_BOLD "\e[1;33m" 
#define BLUE_BOLD "\e[1;34m" 
#define PURPLE_BOLD "\e[1;35m" 
#define CYAN_BOLD "\e[1;36m" 
#define WHITE_BOLD "\e[1;37m" 
#define BLACK_BACKGROUND "\e[40m"
#define RED_BACKGROUND "\e[41m"
#define GREEN_BACKGROUND "\e[42m"
#define YELLOW_BACKGROUND "\e[43m"
#define BLUE_BACKGROUND "\e[44m"
#define PURPLE_BACKGROUND "\e[45m"
#define CYAN_BACKGROUND "\e[46m"
#define WHITE_BACKGROUND "\e[47m"
#define RESET_COLORS "\e[0m"
#endif